
Login-AzureRmAccount -SubscriptionName "SubscriptionName"

$VAULTNAME = 'OEMProdCMDBTokens'; 
$RESOURCEGROUPNAME= 'ECOEMProdCMDBTokens'
$CRED = CONVERTFROM-JSON -INPUTOBJECT (GET-AZUREKEYVAULTSECRET -VAULTNAME $VAULTNAME | CONVERTTO-JSON)
 
$DETAILS=@()
WRITE-HOST -FOREGROUNDCOLOR CYAN "TOTAL OEM PRODUCTION CMDB Tokens  (OA & FOUNDATION) : $($CRED.COUNT)"
WRITE-HOST ""
 
$I=1
FOREACH($C IN $CRED)
{
    #PULLING THE KEYVAULT SECRETS
    WRITE-PROGRESS -ACTIVITY "GATHERING ACCOUNT DETAILS" -STATUS "FOUND ACCOUNT $($C.TAGS.SERVICEACCOUNT)" -PERCENTCOMPLETE ($I / $($CRED.COUNT)*100)

    $password = (GET-AZUREKEYVAULTSECRET -VAULTNAME $VAULTNAME -name $C.NAME).SECRETVALUETEXT
    
    $DETAILS+=NEW-OBJECT -TYPENAME PSOBJECT -PROPERTY @{
 
    SECRETNAME     = $C.NAME
    SERVICEACCOUNT = $C.TAGS.SERVICEACCOUNT
    PASSWORD       = $password
    PASSWORDLength = $password.Length
    MODIFIEDBY     = $C.TAGS.MODIFIEDBY
    }
 
    $I+=1
}
 
WRITE-HOST -FOREGROUNDCOLOR CYAN "TOTAL OEM PRODUCTION SERVICE ACCOUNTS (OA & FOUNDATION) : $($CRED.COUNT)"
$DETAILS |SELECT SECRETNAME,SERVICEACCOUNT,PASSWORD,PASSWORDLength| FT -AUTOSIZE