
# Pre-Requisites
# In case you doesn’t have above modules, install it, using below command or from PowerShell Gallery and search\download for above  mentioned modules. 
# INSTALL-MODULE -NAME AZURE INSTALL-MODULE -NAME AZURERM  IMPORT-MODULE AZUREIMPORT-MODULE AZURERM.KEYVAULT 
# If you doesn’t have permission on Key vault use below command after login to the Azure Portal (PowerShell). 
# LOGIN-AZURERMACCOUNT -SUBSCRIPTIONNAME 'MSFT-UST-EC-OEM-OEMACTIVATION-PROD-02' 
# $VAULTNAME = 'ECOEMPRODSERVICEACCOUNTS'; $RESOURCEGROUPNAME= 'ECOEMCREDENTIALSPRODRG'
# SET-AZURERMKEYVAULTACCESSPOLICY -VAULTNAME $VAULTNAME -RESOURCEGROUPNAME $RESOURCEGROUPNAME -USERPRINCIPALNAME `
# "'$((GET-AZURERMCONTEXT).ACCOUNT.ID)'" -PERMISSIONSTOSECRETS ALL 


LOGIN-AZURERMACCOUNT -SUBSCRIPTIONNAME 'MSFT-UST-EC-OEM-OEMACTIVATION-PROD-02' #TO CONNECT AZURE PORTAL USING POWERSHELL
 
$VAULTNAME = 'ECOEMPRODSERVICEACCOUNTS'; $RESOURCEGROUPNAME= 'ECOEMCREDENTIALSPRODRG'
$CRED = CONVERTFROM-JSON -INPUTOBJECT (GET-AZUREKEYVAULTSECRET -VAULTNAME $VAULTNAME | CONVERTTO-JSON)
 
$DETAILS=@()
WRITE-HOST -FOREGROUNDCOLOR CYAN "TOTAL OEM PRODUCTION SERVICE ACCOUNTS (OA & FOUNDATION) : $($CRED.COUNT)"
WRITE-HOST ""
 
$I=1
FOREACH($C IN $CRED)
{
    #PULLING THE KEYVAULT SECRETS
    WRITE-PROGRESS -ACTIVITY "GATHERING ACCOUNT DETAILS" -STATUS "FOUND ACCOUNT $($C.TAGS.SERVICEACCOUNT)" -PERCENTCOMPLETE ($I / $($CRED.COUNT)*100)
    $DETAILS+=NEW-OBJECT -TYPENAME PSOBJECT -PROPERTY @{
 
    SECRETNAME     = $C.NAME
    SERVICEACCOUNT = $C.TAGS.SERVICEACCOUNT
    PASSWORD       = (GET-AZUREKEYVAULTSECRET -VAULTNAME $VAULTNAME $C.NAME).SECRETVALUETEXT
    EXPIRY         = $C.EXPIRES
    MODIFIEDBY     = $C.TAGS.MODIFIEDBY
    COMMENTS       = $C.TAGS.COMMENT }
 
    $I+=1
}
 
CLS
WRITE-HOST -FOREGROUNDCOLOR CYAN "TOTAL OEM PRODUCTION SERVICE ACCOUNTS (OA & FOUNDATION) : $($CRED.COUNT)"
$DETAILS |SELECT SECRETNAME,SERVICEACCOUNT,PASSWORD,MODIFIEDBY, COMMENTS | FT -AUTOSIZE
